<a href="https://colab.research.google.com/github/Markwema86/Safaricom-2025-Financial-Statements-Analysis/blob/main/Safaricom_Financial_Statements.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### The Income Statement
Consolidated Statement of Profit or Loss.

- **Total Revenue** - The total amount of money generated from the sale of goods or services. It represents the top line of the income statement.
- **Gross Profit** - This is calculated as Total Revenue minus the Cost of Goods Sold (COGS). It indicates how much profit a company makes from its sales after accounting for the direct costs of producing its goods or services.
- **EBITDA** - Earnings Before Interest, Taxes, Depreciation, and Amortization. It's a measure of a company's operating performance, often used to assess a company's profitability without the effects of financing and accounting decisions.
- **Net Profit** - Also known as the bottom line, Net Profit is the amount of money a company has left after all expenses, including operating expenses, interest, and taxes, have been deducted from total revenue.
- **Earnings Per Share (EPS)** - This is a company's Net Profit divided by the number of outstanding shares of its common stock. EPS is a key indicator of a company's profitability and is often used by investors to evaluate a company's financial health.

#### For the year ended 31 March 2025

In [ ]:
# Calculating The Margins
revenue        = 388688900000 # KES billions — fill in
gross_profit   = 287607600000 # KES billions — fill in
ebitda         = 172150900000 # KES billions — fill in
net_profit     = 45757200000 # KES billions — fill in

# Margin calculations
gross_margin   = (gross_profit / revenue) * 100
ebitda_margin  = (ebitda / revenue) * 100
net_margin     = (net_profit / revenue) * 100

print("=== SAFARICOM INCOME STATEMENT ANALYSIS ===\n")
print(f"Revenue:         KES {revenue:.1f}B")
print(f"Gross Profit:    KES {gross_profit:.1f}B  ({gross_margin:.1f}% margin)")
print(f"EBITDA:          KES {ebitda:.1f}B  ({ebitda_margin:.1f}% margin)")
print(f"Net Profit:      KES {net_profit:.1f}B  ({net_margin:.1f}% margin)")

print("\n=== INVESTOR INTERPRETATION ===")

if ebitda_margin >= 40:
    print("EBITDA Margin: EXCEPTIONAL - top quartile globally")
elif ebitda_margin >= 30:
    print("EBITDA Margin: STRONG - highly efficient business")
elif ebitda_margin >= 20:
    print("EBITDA Margin: HEALTHY - industry average")
else:
    print("EBITDA Margin: WATCH - below industry average")

if net_margin >= 20:
    print("Net Margin: EXCEPTIONAL - very profitable")
elif net_margin >= 10:
    print("Net Margin: STRONG - good profitability")
elif net_margin >= 5:
    print("Net Margin: MODERATE - acceptable")
else:
    print("Net Margin: THIN - cost pressure concern")

=== SAFARICOM INCOME STATEMENT ANALYSIS ===

Revenue:         KES 388688900000.0B
Gross Profit:    KES 287607600000.0B  (74.0% margin)
EBITDA:          KES 172150900000.0B  (44.3% margin)
Net Profit:      KES 45757200000.0B  (11.8% margin)

=== INVESTOR INTERPRETATION ===
EBITDA Margin: EXCEPTIONAL - top quartile globally
Net Margin: STRONG - good profitability


### The Balance Sheet

Consolidated Statement of Financial Position in the report.

Looking for six numbers:
- Total Assets - Everything the company owns
- Total Liabilities - Everything it owes
- Total Equity - What belongs to shareholders
- Current Assets - Assets convertible to cash within 1 year
- Current Liabilities - Debts due within 1 year
- Total Debt - Borrowings - bonds, loans, facilities

The golden rule: Assets = Liabilities + Equity.

In [ ]:
# Calculating Balance Sheet Ratios
# Fill in from Safaricom's balance sheet
total_assets       = 515284200000   # KES billions
total_liabilities  = 291263100000   # KES billions
total_equity       = 224021100000   # KES billions
current_assets     = 84049200000   # KES billions
current_liabilities= 431235000000   # KES billions
total_debt         = 159393400000  # KES billions

# Key ratios
current_ratio      = current_assets / current_liabilities
debt_to_equity     = total_debt / total_equity
debt_to_ebitda     = total_debt / ebitda  # uses ebitda from above

print("=== SAFARICOM BALANCE SHEET ANALYSIS ===\n")
print(f"Total Assets:      KES {total_assets:.1f}B")
print(f"Total Liabilities: KES {total_liabilities:.1f}B")
print(f"Total Equity:      KES {total_equity:.1f}B")
print(f"\nKey Ratios:")
print(f"Current Ratio:     {current_ratio:.2f}x")
print(f"Debt/Equity:       {debt_to_equity:.2f}x")
print(f"Debt/EBITDA:       {debt_to_ebitda:.2f}x")

print("\n=== INVESTOR INTERPRETATION ===")

if current_ratio >= 1.5:
    print("Liquidity: STRONG - comfortable short-term position")
elif current_ratio >= 1.0:
    print("Liquidity: ADEQUATE - meets short-term obligations")
else:
    print("Liquidity: WATCH - current liabilities exceed current assets")

if debt_to_ebitda <= 2:
    print("Leverage: CONSERVATIVE - low debt burden")
elif debt_to_ebitda <= 4:
    print("Leverage: MODERATE - manageable debt level")
else:
    print("Leverage: HIGH - significant debt relative to earnings")

=== SAFARICOM BALANCE SHEET ANALYSIS ===

Total Assets:      KES 515284200000.0B
Total Liabilities: KES 291263100000.0B
Total Equity:      KES 224021100000.0B

Key Ratios:
Current Ratio:     0.19x
Debt/Equity:       0.71x
Debt/EBITDA:       0.93x

=== INVESTOR INTERPRETATION ===
Liquidity: WATCH - current liabilities exceed current assets
Leverage: CONSERVATIVE - low debt burden


### The Cash Flow Statement
Consolidated Statement of Cash Flows.

most experienced investors read this first.
Three sections to find:
- Operating Cash Flow    - cash from running the business
- Investing Cash Flow    - cash spent on assets, acquisitions
- Financing Cash Flow    - cash from/to shareholders and lenders
                       
**Net Change in Cash**     - did cash go up or down overall?

The most important number: **Free Cash Flow**

*Operating cash flow = Net cash generated from operating activities

*CapEx = Purchase of property and equipment + Acquisition of intangible assets

In [ ]:
# Free Cash Flow = Operating Cash Flow - Capital Expenditure
operating_cash_flow = 137693900000   # from cash flow statement
capital_expenditure = 73031200000   # usually negative in investing section

free_cash_flow = operating_cash_flow - abs(capital_expenditure)

fcf_margin = (free_cash_flow / revenue) * 100

print("=== SAFARICOM CASH FLOW ANALYSIS ===\n")
print(f"Operating Cash Flow: KES {operating_cash_flow:.1f}B")
print(f"Capital Expenditure: KES {capital_expenditure:.1f}B")
print(f"Free Cash Flow:      KES {free_cash_flow:.1f}B")
print(f"FCF Margin:          {fcf_margin:.1f}%")

# The quality check — is profit backed by real cash?
cash_conversion = (free_cash_flow / net_profit) * 100
print(f"\nCash Conversion:     {cash_conversion:.1f}%")
print("(>80% = profit is real cash, <50% = accounting concern)")

if cash_conversion >= 80:
    print("Verdict: HIGH QUALITY earnings - profit converts to cash")
elif cash_conversion >= 50:
    print("Verdict: MODERATE quality - some non-cash items")
else:
    print("Verdict: LOW quality - profit not converting to cash")

=== SAFARICOM CASH FLOW ANALYSIS ===

Operating Cash Flow: KES 137693900000.0B
Capital Expenditure: KES 73031200000.0B
Free Cash Flow:      KES 64662700000.0B
FCF Margin:          16.6%

Cash Conversion:     141.3%
(>80% = profit is real cash, <50% = accounting concern)
Verdict: HIGH QUALITY earnings - profit converts to cash


Question Analysis

- What is Safaricom's EBITDA margin - and how does it compare to the portfolio companies we built in SQL?

Safaricom's EBITDA margin is 44.3%. According to our investor interpretation, this is considered EXCEPTIONAL and places them in the top quartile globally. afaricom's EBITDA margin is higher than all the portfolio companies we built in SQL

- Is the company's profit backed by real cash - what does the cash conversion ratio tell you?

Yes, the company's profit is strongly backed by real cash. The cash conversion ratio is 141.3%. This high ratio (well above 80%) indicates HIGH QUALITY earnings, meaning that the company's reported profits are effectively converting into actual cash flow.

- Looking at the debt-to-EBITDA .. would Safaricom pass the PE debt screen we built earlier?

Safaricom's Debt-to-EBITDA ratio is 0.93x. Based on the investment criteria, this is considered CONSERVATIVE and indicates a low debt burden. This level of leverage suggests it would likely pass a typical PE debt screen, which often looks for ratios below 2x to 4x.

- What surprised you most about the actual numbers - something you didn't expect?

The Current Ratio is 0.19x, which is interpreted as WATCH - current liabilities exceed current assets. This indicates a potential short-term liquidity concern, which stands in contrast to the otherwise strong profitability (EBITDA and Net Margins) and excellent cash conversion. This is a point that analysts might scrutinize further.

###The Safaricom Paradox - Why 0.19x Current Ratio Isn't A Crisis
A current ratio below 1.0 normally signals danger. But Safaricom is one of the most financially healthy companies in Africa.

How?

Three reasons telecom and fintech companies can safely run low current ratios:
1. **Negative Working Capital Business Model**

Safaricom collects cash from customers before delivering the service. When you buy airtime or deposit M-Pesa float, Safaricom holds your cash immediately. They pay their suppliers later. This means their current liabilities (money owed to suppliers) naturally exceed current assets - not because they're struggling, but because their business model generates cash upfront.

2. **Predictable Recurring Revenue**

A manufacturer with low current ratio is dangerous - if sales slow, they can't pay bills. Safaricom's 40+ million subscribers pay every month like clockwork. Lenders and suppliers know this, so they extend generous payment terms.

3. **Exceptional Operating Cash Flow**

The cash conversion of 141.3% proves the point. Safaricom generates more cash than its reported profit. A company that generates KES X billion in operating cash flow every year doesn't need to hoard current assets as a buffer.

The professional conclusion:

"Safaricom's current ratio of 0.19x initially appears concerning, but is consistent with a negative working capital business model common in telecoms and fintech. The risk is substantially mitigated by exceptional operating cash flow generation, predictable recurring revenue, and conservative leverage of 0.93x Debt/EBITDA. This is not a liquidity risk - it is a structural feature of the business model."

####Full Safaricom Scorecard

pulling everything together into one investment assessment.

In [5]:
# Complete Safaricom fundamental analysis
# Using actual numbers from the annual report

safaricom = {
    'Company':          'Safaricom PLC',
    'Exchange':         'Nairobi Securities Exchange',
    'Sector':           'Telecom / Fintech',

    # Profitability
    'EBITDA_Margin':    44.3,
    'Net_Margin':       11.8,      # margins opted from earlier/above calclations
    'FCF_Margin':       16.6,      # margins opted from earlier/above calclations

    # Leverage
    'Debt_to_EBITDA':   0.93,
    'Current_Ratio':    0.19,

    # Cash Quality
    'Cash_Conversion':  141.3,
}

print("|==============================================|")
print("|     SAFARICOM  INVESTMENT SCORECARD        |")
print("|==============================================|")

# Score each dimension
scores = {}

# Profitability (0-30)
if safaricom['EBITDA_Margin'] >= 40:
    scores['Profitability'] = 30
elif safaricom['EBITDA_Margin'] >= 30:
    scores['Profitability'] = 22
elif safaricom['EBITDA_Margin'] >= 20:
    scores['Profitability'] = 15
else:
    scores['Profitability'] = 8

# Leverage (0-25)
if safaricom['Debt_to_EBITDA'] <= 1:
    scores['Leverage'] = 25
elif safaricom['Debt_to_EBITDA'] <= 2:
    scores['Leverage'] = 18
elif safaricom['Debt_to_EBITDA'] <= 4:
    scores['Leverage'] = 10
else:
    scores['Leverage'] = 3

# Cash Quality (0-25)
if safaricom['Cash_Conversion'] >= 100:
    scores['Cash_Quality'] = 25
elif safaricom['Cash_Conversion'] >= 80:
    scores['Cash_Quality'] = 18
elif safaricom['Cash_Conversion'] >= 50:
    scores['Cash_Quality'] = 10
else:
    scores['Cash_Quality'] = 3

# Liquidity — adjusted for business model (0-20)
# We adjust because negative working capital is structural
if safaricom['Current_Ratio'] >= 1.5:
    scores['Liquidity'] = 20
elif safaricom['Current_Ratio'] >= 1.0:
    scores['Liquidity'] = 15
elif safaricom['Cash_Conversion'] >= 100:
    # High cash conversion compensates for low current ratio
    scores['Liquidity'] = 14
    print("|  NOTE: Liquidity adjusted — negative working capital")
    print("|  model offset by exceptional cash conversion        ")
else:
    scores['Liquidity'] = 5

total_score = sum(scores.values())
max_score   = 100

verdict = (
    "STRONG BUY"    if total_score >= 80 else
    "BUY"           if total_score >= 65 else
    "HOLD"          if total_score >= 50 else
    "MONITOR"       if total_score >= 35 else
    "AVOID"
)

print("|=============================================|")
for dimension, score in scores.items():
    bar = "█" * (score // 2) + "░" * ((25 - score) // 2)
    print(f"|  {dimension:15} {bar} {score:3}/{'30' if dimension == 'Profitability' else '25'}")

print("|=============================================|")
print(f"|  TOTAL SCORE:     {total_score}/100                      |")
print(f"|  VERDICT:         {verdict:35}|")
print("|=============================================|")

|==============================================|
|     SAFARICOM  INVESTMENT SCORECARD        |
|==============================================|
|  NOTE: Liquidity adjusted — negative working capital
|  model offset by exceptional cash conversion        
|=============================================|
|  Profitability   ███████████████  30/30
|  Leverage        ████████████  25/25
|  Cash_Quality    ████████████  25/25
|  Liquidity       ███████░░░░░  14/25
|=============================================|
|  TOTAL SCORE:     94/100                      |
|  VERDICT:         STRONG BUY                         |
|=============================================|
